name: Upload SARIF File

on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  # This workflow contains a job to build and submit pipeline scan, you will need to customize the build process accordingly and make sure the artifact you build is used as the file input to the pipeline scan file parameter
  upload-sarif:
    # The type of runner that the job will run on
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: veracode-results.sarif

  upload-sca-sarif:
      runs-on: ubuntu-latest

      name: Import SCA SARIF
      steps:
      
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Convert SCA Scan to SARIF
          id: convert
          uses: Veracode/veracode-pipeline-scan-results-to-sarif@v1.0.5
          with:
            pipeline-results-json: sca_results.json
            output-results-sarif: veracode-results.sarif
            source-base-path-1: "^com/veracode:src/main/java/com/veracode"
            source-base-path-2: "^WEB-INF:src/main/webapp/WEB-INF"
            finding-rule-level: "3:1:0"
